"""Migración inicial de la base de datos

Revision ID: cda75e639b49
Revises: 
Create Date: 2024-09-19 15:26:43.033396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda75e639b49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modelo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('linea', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('edicion', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('marca_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'marca', ['marca_id'], ['id'])
        batch_op.drop_column('Linea')
        batch_op.drop_column('Marca')
        batch_op.drop_column('Modelo')
        batch_op.drop_column('Edicion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Edicion', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Modelo', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Marca', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Linea', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('marca_id')
        batch_op.drop_column('edicion')
        batch_op.drop_column('linea')
        batch_op.drop_column('modelo')

    # ### end Alembic commands ###
