"""PAGOS Referencia

Revision ID: ce3e630146d4
Revises: 0a0344adfa39
Create Date: 2024-12-19 21:16:30.799743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3e630146d4'
down_revision = '0a0344adfa39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referencia', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.drop_column('referencia')

    # ### end Alembic commands ###
